version: '3.4'

networks:
  poke-api-dev:
    driver: bridge

services:
  pokeapi:
    image: arterialorc/pokeapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - poke-api-dev
    depends_on:
      - postgres_db
      - redis
    links:
      - "redis"
      
  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 355373
      POSTGRES_DB: pokeAPI
    ports:
      - "5432:5432"
    networks:
      - poke-api-dev
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - poke-api-dev
    volumes:
      - /path/to/local/dаta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=poke-api
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
volumes:
  postgres-data: