version: '3.4'

networks:
  poke-api-dev:
    driver: bridge

services:
  pokeapi:
    image: arterialorc/pokeapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - poke-api-dev
    depends_on:
      - postgres_db
      - redis
    links:
      - "redis"
    env_file:
      - PokeAPI/Env/.env.docker
      
  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    networks:
      - poke-api-dev
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"
    networks:
      - poke-api-dev
    volumes:
      - /path/to/local/dаta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=poke-api
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_DATABASES=16
volumes:
  postgres-data: